# Generated by Django 3.2.4 on 2021-06-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_despacho', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
                ('productos', models.CharField(max_length=30)),
                ('peso', models.PositiveIntegerField()),
                ('medidas', models.CharField(max_length=17)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_envio', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
