# Generated by Django 3.2.4 on 2021-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='fecha_envio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='fecha_ingreso',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='numero_despacho',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='peso',
            field=models.CharField(max_length=10),
        ),
    ]
